### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by mthw0** [Foxboron/sbctl#118]
I've successfully used this tool in the past (last week), but today I reinstalled my system and I keep getting this error when trying to run `sbctl verify` :
```
Verifying file database and EFI images in /boot...
✓ /boot/EFI/systemd/systemd-bootx64.efi is signed
✓ /boot/vmlinuz-linux-mainline is signed
✓ /boot/vmlinuz-linux-zen is signed
panic: runtime error: slice bounds out of range [:120696] with capacity 118785

goroutine 1 [running]:
github.com/foxboron/go-uefi/efi/pecoff.GetSignatureBytesFromFile({0xc0002be000, 0xc0002b0580, 0x1d001})
        github.com/foxboron/go-uefi@v0.0.0-20211120193624-3d898a764ffd/efi/pecoff/signature.go:113 +0xb4
github.com/foxboron/go-uefi/efi/pecoff.GetSignatures({0xc0002be000, 0xc00013c630, 0xc00019f900})
        github.com/foxboron/go-uefi@v0.0.0-20211120193624-3d898a764ffd/efi/pecoff/reader.go:13 +0x33
github.com/foxboron/sbctl.VerifyFile({0xc00013c630, 0x24}, {0xc0000a2260, 0x1a})
        github.com/foxboron/sbctl/keys.go:128 +0x185
main.glob..func9.2({0xc0000a2260, 0x1a}, {0x1b, 0x100}, {0x0, 0x0})
        github.com/foxboron/sbctl/cmd/sbctl/verify.go:69 +0xae
path/filepath.walk({0xc0000a2260, 0x1a}, {0x55a114f420f0, 0xc0001a4c30}, 0x55a114f36600)
        path/filepath/path.go:418 +0x125
path/filepath.walk({0xc0001309c0, 0xe}, {0x55a114f420f0, 0xc0001a4a90}, 0x55a114f36600)
        path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc000130950, 0x9}, {0x55a114f420f0, 0xc0001a48f0}, 0x55a114f36600)
        path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc000212040, 0x5}, {0x55a114f420f0, 0xc0001a45b0}, 0x55a114f36600)
        path/filepath/path.go:442 +0x28f
path/filepath.Walk({0xc000212040, 0x5}, 0x55a114f36600)
        path/filepath/path.go:505 +0x6c
main.glob..func9(0x55a11511c620, {0x55a114d0e48e, 0x0, 0x0})
        github.com/foxboron/sbctl/cmd/sbctl/verify.go:50 +0xbb
github.com/spf13/cobra.(*Command).execute(0x55a11511c620, {0x55a115153588, 0x0, 0x0})
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x55a11511d520)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        github.com/foxboron/sbctl/cmd/sbctl/main.go:79 +0xf2
```
It prints already signed files and then prints this error. Everything worked 100% before, that's why I am confused. I have managed to create and enroll my keys just fine I also managed to sign some files so Secure boot is working.
IIRC the first time I ran `sbctl verify` it worked correctly, which is weird.

**Comment by Foxboron** [comment]
Hmm, what files do you have on your boot partition?

I assume there is a file there which `sbctl` thinks is a EFI Executable but isn't.

`find /boot` and the output of `sbctl list-files`  please

**Comment by mthw0** [comment]
```
/boot
/boot/loader
/boot/loader/entries
/boot/loader/entries/zen.conf
/boot/loader/entries/mainline.conf
/boot/loader/entries/lts.conf
/boot/loader/entries/hard.conf
/boot/loader/entries/raven.conf
/boot/loader/entries/lts2.conf
/boot/loader/entries/clear.conf
/boot/loader/loader.conf
/boot/loader/random-seed
/boot/EFI
/boot/EFI/Microsoft
/boot/EFI/Microsoft/Boot
/boot/EFI/Microsoft/Boot/bg-BG
/boot/EFI/Microsoft/Boot/bg-BG/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/bg-BG/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/kd_0C_8086.dll
/boot/EFI/Microsoft/Boot/cs-CZ
/boot/EFI/Microsoft/Boot/cs-CZ/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/cs-CZ/memtest.efi.mui
/boot/EFI/Microsoft/Boot/cs-CZ/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/da-DK
/boot/EFI/Microsoft/Boot/da-DK/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/da-DK/memtest.efi.mui
/boot/EFI/Microsoft/Boot/da-DK/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/de-DE
/boot/EFI/Microsoft/Boot/de-DE/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/de-DE/memtest.efi.mui
/boot/EFI/Microsoft/Boot/de-DE/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/el-GR
/boot/EFI/Microsoft/Boot/el-GR/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/el-GR/memtest.efi.mui
/boot/EFI/Microsoft/Boot/el-GR/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/en-GB
/boot/EFI/Microsoft/Boot/en-GB/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/en-GB/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/en-US
/boot/EFI/Microsoft/Boot/en-US/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/en-US/memtest.efi.mui
/boot/EFI/Microsoft/Boot/en-US/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/es-ES
/boot/EFI/Microsoft/Boot/es-ES/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/es-ES/memtest.efi.mui
/boot/EFI/Microsoft/Boot/es-ES/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/es-MX
/boot/EFI/Microsoft/Boot/es-MX/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/es-MX/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/et-EE
/boot/EFI/Microsoft/Boot/et-EE/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/et-EE/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/fi-FI
/boot/EFI/Microsoft/Boot/fi-FI/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/fi-FI/memtest.efi.mui
/boot/EFI/Microsoft/Boot/fi-FI/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/fr-CA
/boot/EFI/Microsoft/Boot/fr-CA/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/fr-CA/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/fr-FR
/boot/EFI/Microsoft/Boot/fr-FR/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/fr-FR/memtest.efi.mui
/boot/EFI/Microsoft/Boot/fr-FR/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/hr-HR
/boot/EFI/Microsoft/Boot/hr-HR/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/hr-HR/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/hu-HU
/boot/EFI/Microsoft/Boot/hu-HU/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/hu-HU/memtest.efi.mui
/boot/EFI/Microsoft/Boot/hu-HU/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/it-IT
/boot/EFI/Microsoft/Boot/it-IT/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/it-IT/memtest.efi.mui
/boot/EFI/Microsoft/Boot/it-IT/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/ja-JP
/boot/EFI/Microsoft/Boot/ja-JP/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/ja-JP/memtest.efi.mui
/boot/EFI/Microsoft/Boot/ja-JP/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/ko-KR
/boot/EFI/Microsoft/Boot/ko-KR/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/ko-KR/memtest.efi.mui
/boot/EFI/Microsoft/Boot/ko-KR/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/lt-LT
/boot/EFI/Microsoft/Boot/lt-LT/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/lt-LT/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/lv-LV
/boot/EFI/Microsoft/Boot/lv-LV/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/lv-LV/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/bootmgfw.efi
/boot/EFI/Microsoft/Boot/nb-NO
/boot/EFI/Microsoft/Boot/nb-NO/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/nb-NO/memtest.efi.mui
/boot/EFI/Microsoft/Boot/nb-NO/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/nl-NL
/boot/EFI/Microsoft/Boot/nl-NL/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/nl-NL/memtest.efi.mui
/boot/EFI/Microsoft/Boot/nl-NL/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/pl-PL
/boot/EFI/Microsoft/Boot/pl-PL/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/pl-PL/memtest.efi.mui
/boot/EFI/Microsoft/Boot/pl-PL/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/pt-BR
/boot/EFI/Microsoft/Boot/pt-BR/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/pt-BR/memtest.efi.mui
/boot/EFI/Microsoft/Boot/pt-BR/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/pt-PT
/boot/EFI/Microsoft/Boot/pt-PT/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/pt-PT/memtest.efi.mui
/boot/EFI/Microsoft/Boot/pt-PT/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/qps-ploc
/boot/EFI/Microsoft/Boot/qps-ploc/memtest.efi.mui
/boot/EFI/Microsoft/Boot/ro-RO
/boot/EFI/Microsoft/Boot/ro-RO/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/ro-RO/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/ru-RU
/boot/EFI/Microsoft/Boot/ru-RU/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/ru-RU/memtest.efi.mui
/boot/EFI/Microsoft/Boot/ru-RU/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/sk-SK
/boot/EFI/Microsoft/Boot/sk-SK/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/sk-SK/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/sl-SI
/boot/EFI/Microsoft/Boot/sl-SI/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/sl-SI/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/sr-Latn-RS
/boot/EFI/Microsoft/Boot/sr-Latn-RS/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/sr-Latn-RS/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/sv-SE
/boot/EFI/Microsoft/Boot/sv-SE/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/sv-SE/memtest.efi.mui
/boot/EFI/Microsoft/Boot/sv-SE/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/tr-TR
/boot/EFI/Microsoft/Boot/tr-TR/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/tr-TR/memtest.efi.mui
/boot/EFI/Microsoft/Boot/tr-TR/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/uk-UA
/boot/EFI/Microsoft/Boot/uk-UA/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/uk-UA/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/bootmgr.efi
/boot/EFI/Microsoft/Boot/memtest.efi
/boot/EFI/Microsoft/Boot/boot.stl
/boot/EFI/Microsoft/Boot/zh-CN
/boot/EFI/Microsoft/Boot/zh-CN/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/zh-CN/memtest.efi.mui
/boot/EFI/Microsoft/Boot/zh-CN/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/zh-TW
/boot/EFI/Microsoft/Boot/zh-TW/bootmgr.efi.mui
/boot/EFI/Microsoft/Boot/zh-TW/memtest.efi.mui
/boot/EFI/Microsoft/Boot/zh-TW/bootmgfw.efi.mui
/boot/EFI/Microsoft/Boot/BOOTSTAT.DAT
/boot/EFI/Microsoft/Boot/Fonts
/boot/EFI/Microsoft/Boot/Fonts/segmono_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/segoen_slboot.ttf
/boot/EFI/Microsoft/Boot/Fonts/segoe_slboot.ttf
/boot/EFI/Microsoft/Boot/Fonts/chs_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/cht_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/jpn_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/kor_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/malgunn_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/malgun_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/meiryon_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/meiryo_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/msjhn_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/msjh_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/msyhn_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/msyh_boot.ttf
/boot/EFI/Microsoft/Boot/Fonts/wgl4_boot.ttf
/boot/EFI/Microsoft/Boot/Resources
/boot/EFI/Microsoft/Boot/Resources/cs-CZ
/boot/EFI/Microsoft/Boot/Resources/cs-CZ/bootres.dll.mui
/boot/EFI/Microsoft/Boot/Resources/en-US
/boot/EFI/Microsoft/Boot/Resources/en-US/bootres.dll.mui
/boot/EFI/Microsoft/Boot/Resources/hu-HU
/boot/EFI/Microsoft/Boot/Resources/hu-HU/bootres.dll.mui
/boot/EFI/Microsoft/Boot/Resources/pl-PL
/boot/EFI/Microsoft/Boot/Resources/pl-PL/bootres.dll.mui
/boot/EFI/Microsoft/Boot/Resources/bootres.dll
/boot/EFI/Microsoft/Boot/winsipolicy.p7b
/boot/EFI/Microsoft/Boot/kdnet_uart16550.dll
/boot/EFI/Microsoft/Boot/kdstub.dll
/boot/EFI/Microsoft/Boot/kd_02_10df.dll
/boot/EFI/Microsoft/Boot/kd_02_10ec.dll
/boot/EFI/Microsoft/Boot/kd_02_1137.dll
/boot/EFI/Microsoft/Boot/kd_02_14e4.dll
/boot/EFI/Microsoft/Boot/kd_02_15b3.dll
/boot/EFI/Microsoft/Boot/kd_02_1969.dll
/boot/EFI/Microsoft/Boot/kd_02_19a2.dll
/boot/EFI/Microsoft/Boot/kd_02_1af4.dll
/boot/EFI/Microsoft/Boot/kd_02_8086.dll
/boot/EFI/Microsoft/Boot/BCD
/boot/EFI/Microsoft/Boot/BCD.LOG
/boot/EFI/Microsoft/Boot/BCD.LOG1
/boot/EFI/Microsoft/Boot/BCD.LOG2
/boot/EFI/Microsoft/Boot/kd_07_1415.dll
/boot/EFI/Microsoft/Boot/CIPolicies
/boot/EFI/Microsoft/Boot/CIPolicies/Active
/boot/EFI/Microsoft/Boot/CIPolicies/Active/{5DAC656C-21AD-4A02-AB49-649917162E70}.cip
/boot/EFI/Microsoft/Boot/CIPolicies/Active/{82443e1e-8a39-4b4a-96a8-f40ddc00b9f3}.cip
/boot/EFI/Microsoft/Boot/CIPolicies/Active/{CDD5CB55-DB68-4D71-AA38-3DF2B6473A52}.cip
/boot/EFI/Microsoft/Recovery
/boot/EFI/Microsoft/Recovery/BCD
/boot/EFI/Microsoft/Recovery/BCD.LOG
/boot/EFI/Microsoft/Recovery/BCD.LOG1
/boot/EFI/Microsoft/Recovery/BCD.LOG2
/boot/EFI/Boot
/boot/EFI/Boot/bootx64.efi
/boot/EFI/systemd
/boot/EFI/systemd/systemd-bootx64.efi
/boot/EFI/Linux
/boot/amd-ucode.img
/boot/vmlinuz-linux-zen
/boot/vmlinuz-linux-mainline
/boot/initramfs-linux-mainline.img
/boot/initramfs-linux-zen.img
/boot/initramfs-linux-zen-fallback.img
/boot/System Volume Information
/boot/System Volume Information/ClientRecoveryPasswordRotation
/boot/System Volume Information/AadRecoveryPasswordDelete
/boot/initramfs-linux-mainline-fallback.img
/boot/vmlinuz
/boot/723ba35ad7214543907fd4cda42286cf
/boot/System.map

```
and

```

/boot/EFI/systemd/systemd-bootx64.efi
Signed:         ✓ Signed

/boot/vmlinuz-linux-mainline
Signed:         ✓ Signed

/boot/vmlinuz-linux-zen
Signed:         ✓ Signed

```

**Comment by mthw0** [comment]
Since signing `/boot/EFI/Boot/bootx64.efi` fails with the same error could it be the file?

**Comment by Foxboron** [comment]
Is `/boot/EFI/Boot/bootx64.efi` the Windows bootloader or systemd-boot? Had a few issues in `sbctl` with the Windows files present :)

**Comment by mthw0** [comment]
It originally belongs Windows IIRC, but it has been overwritten by systemd-boot which has two files
 `/boot/EFI/systemd/systemd-bootx64.efi` and `/boot/EFI/BOOT/BOOTX64.EFI`. It's not needed for either of OSes to boot since I only signed the first one and both Linux and Windows boot normally. Since I didn't have this issue a while ago and recently there has been a new version of Systemd (250), something might have changed on their end, or a possible bug?

**Comment by Foxboron** [comment]
Please run `sudo strace -e trace=openat sbctl verify`

**Comment by mthw0** [comment]
I've found the issue. It was caused by `/boot/EFI/BOOT/BOOTX64.EFI` but the reason was that it has been corrupted.
Deleting it and copying a new one fixes the problem. Now it can be signed and _verify_ doesn't show any errors anymore.
It does, however, show all windows files as unsigned and shows both `/boot/EFI/BOOT/BOOTX64.EFI` and `/boot/EFI/Boot/bootx64.efi` even though the first one doesn't exist (is fat32 case insensitive?).

**Comment by Foxboron** [comment]
FAT is case insensitive, yes.

But I don't think this should panic if the file is corrupted. So I'll add some lines to `go-uefi` so we don't just get a panic.

**Comment by Foxboron** [comment]
I'll pull this change whenever I do a new sbctl release :)

https://github.com/Foxboron/go-uefi/commit/3ffd1128196221bd39636be20b689d8797c97afc

**Comment by nekopsykose** [comment]
there was a new sbctl release on april (0.9), but going by the go.mod the go-uefi version is v0.0.0-20211120193624-3d898a764ffd, which predates the above fix by one commit (and so this issue sometimes still shows up, though strangely deleting and regenerating the files in /boot fixes it..)
