### ISSUE TITLE
[bug] sbctl enroll-keys/verify fails with segmentation violation

### ISSUE THREAD

**Issue by UserCel** [Foxboron/sbctl#375]
OS: EneavourOS
Kernel: Linux 6.10.10-zen1-1-zen
Package:
```
pacman -Qi sbctl
Name            : sbctl
Version         : 0.15.4-1
Description     : Secure Boot key manager
Architecture    : x86_64
URL             : https://github.com/Foxboron/sbctl
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : binutils  util-linux
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 8.77 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Wed 07 Aug 2024 15:33:09
Install Date    : Sat 21 Sep 2024 11:46:08
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
Error:
```
sbctl enroll-keys
Enrolling keys to EFI variables...panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x641b4ae0bf9c]

goroutine 1 [running]:
github.com/foxboron/sbctl/backend.GetBackendType({0xc00018a400?, 0x641b4b330820?, 0xc000032ec0?})
        github.com/foxboron/sbctl/backend/backend.go:305 +0x1c
github.com/foxboron/sbctl/backend.readKey(0xc000280c00, {0xc000292168?, 0xc0000061c0?}, 0x10000000000?, 0x3)
        github.com/foxboron/sbctl/backend/backend.go:253 +0x3b2
github.com/foxboron/sbctl/backend.GetKeyBackend(0x0?, 0x0?)
        github.com/foxboron/sbctl/backend/backend.go:276 +0x45
github.com/foxboron/sbctl/backend.GetKeyHierarchy({0x200000003?, 0x0?}, 0xc000280c00)
        github.com/foxboron/sbctl/backend/backend.go:282 +0x25
main.KeySync(0xc000280c00, {0xc000043aa8, 0x0, 0x22?})
        github.com/foxboron/sbctl/cmd/sbctl/enroll-keys.go:87 +0x4d
main.RunEnrollKeys(0xc000280c00)
        github.com/foxboron/sbctl/cmd/sbctl/enroll-keys.go:323 +0x61d
main.init.func4(0xc0002a0400?, {0x641b4ae94403?, 0x4?, 0x641b4ae94407?})
        github.com/foxboron/sbctl/cmd/sbctl/enroll-keys.go:70 +0x6a
github.com/spf13/cobra.(*Command).execute(0x641b4b291200, {0x641b4b330820, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x641b4b292620)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.8.1/command.go:1034
main.main()
        github.com/foxboron/sbctl/cmd/sbctl/main.go:166 +0x5a7
```
```
sbctl verify
Verifying file database and EFI images in /efi...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x58afb96d9f9c]

goroutine 1 [running]:
github.com/foxboron/sbctl/backend.GetBackendType({0xc00018a600?, 0x58afb9bfe820?, 0xc000032de0?})
        github.com/foxboron/sbctl/backend/backend.go:305 +0x1c
github.com/foxboron/sbctl/backend.readKey(0xc0001ac360, {0xc000028678?, 0x1?}, 0xc0000435b0?, 0x3)
        github.com/foxboron/sbctl/backend/backend.go:253 +0x3b2
github.com/foxboron/sbctl/backend.GetKeyBackend(0xc0000151ba?, 0x2?)
        github.com/foxboron/sbctl/backend/backend.go:276 +0x45
github.com/foxboron/sbctl/backend.GetKeyHierarchy({0x58afb98e3298?, 0xc00007c270?}, 0xc0001ac360)
        github.com/foxboron/sbctl/backend/backend.go:282 +0x25
main.VerifyOneFile(0xc0001ac360, {0xc00002e980, 0x3b})
        github.com/foxboron/sbctl/cmd/sbctl/verify.go:46 +0x2ab
main.RunVerify.func2({0xc00002e980, 0x3b}, {0xffffffffffffff9c?, 0xc00002e980?}, {0x0?, 0x0?})
        github.com/foxboron/sbctl/cmd/sbctl/verify.go:117 +0x125
github.com/spf13/afero.walk({0x58afb98ea200, 0x58afb9bfe820}, {0xc00002e980, 0x3b}, {0x58afb98e8448, 0xc0001b61a0}, 0xc000043b30)
        github.com/spf13/afero@v1.11.0/path.go:44 +0x6c
github.com/spf13/afero.walk({0x58afb98ea200, 0x58afb9bfe820}, {0xc00002e700, 0x35}, {0x58afb98e8448, 0xc0001a5ba0}, 0xc000043b30)
        github.com/spf13/afero@v1.11.0/path.go:69 +0x2e5
github.com/spf13/afero.walk({0x58afb98ea200, 0x58afb9bfe820}, {0xc000030ab0, 0x25}, {0x58afb98e8448, 0xc0001a5a00}, 0xc000043b30)
        github.com/spf13/afero@v1.11.0/path.go:69 +0x2e5
github.com/spf13/afero.walk({0x58afb98ea200, 0x58afb9bfe820}, {0xc0000150a4, 0x4}, {0x58afb98e8448, 0xc0001a5860}, 0xc000043b30)
        github.com/spf13/afero@v1.11.0/path.go:69 +0x2e5
github.com/spf13/afero.Walk({0x58afb98ea200, 0x58afb9bfe820}, {0xc0000150a4, 0x4}, 0xc000043b30)
        github.com/spf13/afero@v1.11.0/path.go:105 +0x7a
main.RunVerify(0xc000189700?, {0x58afb9bfe820, 0x0, 0x58afb9762407?})
        github.com/foxboron/sbctl/cmd/sbctl/verify.go:107 +0x38e
github.com/spf13/cobra.(*Command).execute(0x58afb9b62000, {0x58afb9bfe820, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x58afb9b60620)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.8.1/command.go:1034
main.main()
        github.com/foxboron/sbctl/cmd/sbctl/main.go:166 +0x5a7
```
Thanks

**Comment by Foxboron** [comment]
There isn't enough information to reproduce the issue. 

Please include the output of `sbctl setup --print-config` and preferably some more details on how you setup `sbctl`.

**Comment by UserCel** [comment]
Thanks for taking note!
I've setup sbctl according to the [ArchWiki](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#Assisted_process_with_sbctl). I've done the same on different hardware with no issue.
Perhaps it's useful to add that this is on an Asus ROG Flow X13 GV302XV.

```
sbctl setup --print-config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x63afb9bedf9c]

goroutine 1 [running]:
github.com/foxboron/sbctl/backend.GetBackendType({0xc000242000?, 0x63afba112820?, 0xc000218300?})
        github.com/foxboron/sbctl/backend/backend.go:305 +0x1c
github.com/foxboron/sbctl/backend.readKey(0xc000025800, {0xc00021e168?, 0x4?}, 0xc000043aa0?, 0x3)
        github.com/foxboron/sbctl/backend/backend.go:253 +0x3b2
github.com/foxboron/sbctl/backend.GetKeyBackend(0x63afb9c7641b?, 0x4?)
        github.com/foxboron/sbctl/backend/backend.go:276 +0x45
github.com/foxboron/sbctl/backend.GetKeyHierarchy({0x63afb98cbde6?, 0x0?}, 0xc000025800)
        github.com/foxboron/sbctl/backend/backend.go:282 +0x25
main.PrintConfig(0xc000025800)
        github.com/foxboron/sbctl/cmd/sbctl/setup.go:53 +0xb7
main.RunSetup(0xc00022ca00?, {0x63afb9c76403?, 0x4?, 0x63afb9c76407?})
        github.com/foxboron/sbctl/cmd/sbctl/setup.go:228 +0xa5
github.com/spf13/cobra.(*Command).execute(0x63afba075480, {0xc0002022b0, 0x1, 0x1})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x63afba074620)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.8.1/command.go:1034
main.main()
        github.com/foxboron/sbctl/cmd/sbctl/main.go:166 +0x5a7
```

Most command line options simply fail similarly.

**Comment by Foxboron** [comment]
There isn't enough information to figure out why this is happening. I suspect the files are broken in some way? Can you give the directory listing of `/var/lib/sbctl` and probably check the keyfiles that they are properly created? Does this happen if you rm the `/var/lib/sbctl/` directory and recreate everything?

**Comment by UserCel** [comment]
> There isn't enough information to figure out why this is happening. I suspect the files are broken in some way? Can you give the directory listing of `/var/lib/sbctl` and probably check the keyfiles that they are properly created? Does this happen if you rm the `/var/lib/sbctl/` directory and recreate everything?

Removing `/var/lib/sbctl/` and recreating the keys seems to gave been the solution.
Thanks, don't know why this happened.
